version: '3.8'

services:
  app:
    build: .
    container_name: llm_data_engineering_app
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.5"
          memory: "512M"
    env_file:
      - .env
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=review_database
      - DB_USER=data_scientist
      - DB_PASSWORD=default123
    ports:
      - "8000:8000"  # Map to API port in Dockerfile
    volumes:
      - ./data:/app/data

  db:
    image: postgres:13
    container_name: postgres_container
    env_file:
      - .env
    environment:
      POSTGRES_DB: review_database
      POSTGRES_USER: data_scientist
      POSTGRES_PASSWORD: default123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=yourpassword
    volumes:
      - ./monitoring/grafana:/etc/grafana
    ports:
      - "3000:3000"

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

  dashboard:
    build:
      context: ./dashboard
    ports:
      - "8501:8501"
    depends_on:
      - app

volumes:
  postgres_data:
