global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'fastapi'
    scrape_interval: 5s
    static_configs:
      - targets: ['app:8000']

rule_files:
  - /etc/prometheus/fastapi_rules.yml
